import { HttpService } from '@nestjs/axios';
import { Injectable } from '@nestjs/common';
import { lastValueFrom } from 'rxjs';

@Injectable()
export class GooglePlaceApiService {
  constructor(private httpService: HttpService) {}
  googleApiResponse = [
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Nakwon Korean Restaurant(NorthYork)',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJs6vPuA0tK4gRHMHV8D0_4L4',
      plus_code: {
        compound_code: 'QHHM+QM North York, Toronto, ON, Canada',
        global_code: '87M2QHHM+QM',
      },
      price_level: 1,
      rating: 3.7,
      reference: 'ChIJs6vPuA0tK4gRHMHV8D0_4L4',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 801,
      vicinity: '5594 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/bar_pinlet',
      name: "Puck 'N Wings",
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJa1NFCw4tK4gR_cyXlWGUSCM',
      plus_code: {
        compound_code: 'QHJM+5R North York, Toronto, ON, Canada',
        global_code: '87M2QHJM+5R',
      },
      price_level: 2,
      rating: 3.6,
      reference: 'ChIJa1NFCw4tK4gR_cyXlWGUSCM',
      scope: 'GOOGLE',
      types: [
        'bar',
        'restaurant',
        'food',
        'point_of_interest',
        'establishment',
      ],
      user_ratings_total: 963,
      vicinity: '5625 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Kayagum Restaurant',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJ8YfkcA0tK4gR-3hI07cbLKI',
      plus_code: {
        compound_code: 'QHGM+XW North York, Toronto, ON, Canada',
        global_code: '87M2QHGM+XW',
      },
      price_level: 2,
      rating: 3.8,
      reference: 'ChIJ8YfkcA0tK4gR-3hI07cbLKI',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 1008,
      vicinity: '5460 Yonge Street #100, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Burrito Place',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJndTxag4tK4gRfSxXIjkzhbM',
      plus_code: {
        compound_code: 'QHJM+GP North York, Toronto, ON, Canada',
        global_code: '87M2QHJM+GP',
      },
      price_level: 2,
      rating: 4,
      reference: 'ChIJndTxag4tK4gRfSxXIjkzhbM',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 415,
      vicinity: '5653 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Tim Hortons',
      photos: [[Object]],
      place_id: 'ChIJfXvl_2QtK4gRdIjLf-M04uM',
      plus_code: {
        compound_code: 'QHJM+9H North York, Toronto, ON, Canada',
        global_code: '87M2QHJM+9H',
      },
      price_level: 1,
      rating: 3.8,
      reference: 'ChIJfXvl_2QtK4gRdIjLf-M04uM',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 230,
      vicinity: '5695 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Thai Express Restaurant Toronto',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJvW8P1w0tK4gR-hWFNzCJ1qE',
      plus_code: {
        compound_code: 'QHJM+3C North York, Toronto, ON, Canada',
        global_code: '87M2QHJM+3C',
      },
      price_level: 1,
      rating: 3.9,
      reference: 'ChIJvW8P1w0tK4gR-hWFNzCJ1qE',
      scope: 'GOOGLE',
      types: [
        'meal_takeaway',
        'restaurant',
        'food',
        'point_of_interest',
        'establishment',
      ],
      user_ratings_total: 120,
      vicinity: '5650 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Freshii',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJvW8P1w0tK4gRozvY5QDoc9w',
      plus_code: {
        compound_code: 'QHJM+3C North York, Toronto, ON, Canada',
        global_code: '87M2QHJM+3C',
      },
      price_level: 2,
      rating: 3.7,
      reference: 'ChIJvW8P1w0tK4gRozvY5QDoc9w',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 187,
      vicinity: '5650 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Piazza Manna',
      opening_hours: { open_now: false },
      photos: [[Object]],
      place_id: 'ChIJBZztCg4tK4gRZ9zDZyntdLo',
      plus_code: {
        compound_code: 'QHJM+2C North York, Toronto, ON, Canada',
        global_code: '87M2QHJM+2C',
      },
      rating: 4.3,
      reference: 'ChIJBZztCg4tK4gRZ9zDZyntdLo',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 39,
      vicinity: '5650 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Tim Hortons',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJhXg848w0K4gR3mpb_F6ZJsk',
      plus_code: {
        compound_code: 'QHMM+4J North York, Toronto, ON, Canada',
        global_code: '87M2QHMM+4J',
      },
      price_level: 1,
      rating: 3.7,
      reference: 'ChIJhXg848w0K4gR3mpb_F6ZJsk',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 455,
      vicinity: '5765 Yonge Street Apt 1401, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Hashi Izakaya',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJiQJWlQ0tK4gRy1sHiYzfVXE',
      plus_code: {
        compound_code: 'QHHM+MP North York, Toronto, ON, Canada',
        global_code: '87M2QHHM+MP',
      },
      price_level: 2,
      rating: 4.1,
      reference: 'ChIJiQJWlQ0tK4gRy1sHiYzfVXE',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 466,
      vicinity: '5582 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: "Pumpernickel's",
      opening_hours: { open_now: false },
      photos: [[Object]],
      place_id: 'ChIJGfsFYw4tK4gRXVQvX6xATAA',
      plus_code: {
        compound_code: 'QHHJ+QQ North York, Toronto, ON, Canada',
        global_code: '87M2QHHJ+QQ',
      },
      price_level: 2,
      rating: 3.7,
      reference: 'ChIJGfsFYw4tK4gRXVQvX6xATAA',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 324,
      vicinity: '5700 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'MABU Station',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJ72ajcA0tK4gRGiv6IRTKFVY',
      plus_code: {
        compound_code: 'QHGP+X4 North York, Toronto, ON, Canada',
        global_code: '87M2QHGP+X4',
      },
      price_level: 2,
      rating: 3.7,
      reference: 'ChIJ72ajcA0tK4gRGiv6IRTKFVY',
      scope: 'GOOGLE',
      types: [
        'cafe',
        'restaurant',
        'food',
        'store',
        'point_of_interest',
        'establishment',
      ],
      user_ratings_total: 777,
      vicinity: '5455 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Magic Noodle',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJhcW2ew0tK4gRuxMQN3FVvy4',
      plus_code: {
        compound_code: 'QHGP+X4 North York, Toronto, ON, Canada',
        global_code: '87M2QHGP+X4',
      },
      price_level: 1,
      rating: 3.9,
      reference: 'ChIJhcW2ew0tK4gRuxMQN3FVvy4',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 958,
      vicinity: '5453 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Pyung Won House',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJF2r76Q0tK4gR55QEofDN6ns',
      plus_code: {
        compound_code: 'QHHM+PM North York, Toronto, ON, Canada',
        global_code: '87M2QHHM+PM',
      },
      price_level: 2,
      rating: 3.5,
      reference: 'ChIJF2r76Q0tK4gR55QEofDN6ns',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 350,
      vicinity: '5588 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Angus Pho House',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJN9tUZA0tK4gRWCvCFF3AqlU',
      plus_code: {
        compound_code: 'QHGP+R5 North York, Toronto, ON, Canada',
        global_code: '87M2QHGP+R5',
      },
      price_level: 1,
      rating: 4,
      reference: 'ChIJN9tUZA0tK4gRWCvCFF3AqlU',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 673,
      vicinity: '5443 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Tim Hortons',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJUXT1kw0tK4gRcKduOP6J6hw',
      plus_code: {
        compound_code: 'QHHP+J2 North York, Toronto, ON, Canada',
        global_code: '87M2QHHP+J2',
      },
      price_level: 1,
      rating: 3.8,
      reference: 'ChIJUXT1kw0tK4gRcKduOP6J6hw',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 218,
      vicinity: '5571 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Pizza Nova',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJRRqM6A0tK4gRzzOYEpGX-Sg',
      plus_code: {
        compound_code: 'QHHM+RW Toronto, ON, Canada',
        global_code: '87M2QHHM+RW',
      },
      price_level: 1,
      rating: 3.9,
      reference: 'ChIJRRqM6A0tK4gRzzOYEpGX-Sg',
      scope: 'GOOGLE',
      types: [
        'meal_delivery',
        'meal_takeaway',
        'restaurant',
        'food',
        'point_of_interest',
        'establishment',
      ],
      user_ratings_total: 168,
      vicinity: '5585 Yonge Street, Toronto',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
      name: 'Buk Chang Dong Soon Tofu',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJN2UnZQ0tK4gRXQ-sUakD0-4',
      plus_code: {
        compound_code: 'QHGP+V5 North York, Toronto, ON, Canada',
        global_code: '87M2QHGP+V5',
      },
      price_level: 1,
      rating: 4.3,
      reference: 'ChIJN2UnZQ0tK4gRXQ-sUakD0-4',
      scope: 'GOOGLE',
      types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
      user_ratings_total: 1337,
      vicinity: '5445 Yonge Street, North York',
    },
    {
      business_status: 'CLOSED_TEMPORARILY',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
      icon_background_color: '#7B9EB0',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet',
      name: '超级玩家 Super E-sports Cafe (North York)',
      permanently_closed: true,
      photos: [[Object]],
      place_id: 'ChIJTwlVISAtK4gR7XSwSoyif-k',
      plus_code: {
        compound_code: 'QHJM+GQ North York, Toronto, ON, Canada',
        global_code: '87M2QHJM+GQ',
      },
      rating: 4.1,
      reference: 'ChIJTwlVISAtK4gR7XSwSoyif-k',
      scope: 'GOOGLE',
      types: [
        'cafe',
        'restaurant',
        'food',
        'point_of_interest',
        'establishment',
      ],
      user_ratings_total: 31,
      vicinity: '5649 Yonge Street, North York',
    },
    {
      business_status: 'OPERATIONAL',
      geometry: { location: [Object], viewport: [Object] },
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/cafe-71.png',
      icon_background_color: '#FF9E67',
      icon_mask_base_uri:
        'https://maps.gstatic.com/mapfiles/place_api/icons/v2/cafe_pinlet',
      name: 'The Cups (Finch)',
      opening_hours: { open_now: true },
      photos: [[Object]],
      place_id: 'ChIJ03QCRcItK4gRrdlxDZY-FH4',
      plus_code: {
        compound_code: 'QHJM+FQ North York, Toronto, ON, Canada',
        global_code: '87M2QHJM+FQ',
      },
      rating: 4.4,
      reference: 'ChIJ03QCRcItK4gRrdlxDZY-FH4',
      scope: 'GOOGLE',
      types: [
        'cafe',
        'bakery',
        'restaurant',
        'food',
        'store',
        'point_of_interest',
        'establishment',
      ],
      user_ratings_total: 172,
      vicinity: '5647 Yonge Street #2FL, North York',
    },
  ];
  async getNearbyRestaurants(latitude: number, longitude: number) {
    // ========= comment to save api call in development =========

    // const url = `https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=${latitude},${longitude}&radius=500&type=restaurant&key=${process.env.GOOGLE_MAP_API_KEY}`;
    // const response = await lastValueFrom(this.httpService.get(url));
    const data = this.googleApiResponse;
    // create restaurant if doesn't exist in database

    return JSON.stringify(data);
  }
}
